const colors = {
  light: {
    text: "#0B1E3D",
    tint: "#1A6BAF",
    background: "#EEF3FA",
    foreground: "#0B1E3D",
    card: "#FFFFFF",
    cardForeground: "#0B1E3D",
    primary: "#1A6BAF",
    primaryForeground: "#FFFFFF",
    secondary: "#D8E7F5",
    secondaryForeground: "#0B1E3D",
    muted: "#D8E7F5",
    mutedForeground: "#5A7A9B",
    accent: "#4B9FE1",
    accentForeground: "#FFFFFF",
    destructive: "#E74C3C",
    destructiveForeground: "#FFFFFF",
    border: "#C0D5E8",
    input: "#C0D5E8",
    success: "#27AE60",
    warning: "#E67E22",
  },
  dark: {
    text: "#F0F4F8",
    tint: "#4B9FE1",
    background: "#0B1E3D",
    foreground: "#F0F4F8",
    card: "#142B52",
    cardForeground: "#F0F4F8",
    primary: "#4B9FE1",
    primaryForeground: "#0B1E3D",
    secondary: "#1E3A6B",
    secondaryForeground: "#F0F4F8",
    muted: "#1E3A6B",
    mutedForeground: "#8AAFC8",
    accent: "#4B9FE1",
    accentForeground: "#0B1E3D",
    destructive: "#E74C3C",
    destructiveForeground: "#FFFFFF",
    border: "#1E3A6B",
    input: "#1E3A6B",
    success: "#2ECC71",
    warning: "#F39C12",
  },
  radius: 12,
};

export default colors;
